### ISSUE TITLE
SettingsTests.cs test failing because of Xam.Plugins.Settings reference?

### ISSUE THREAD

**Issue by sli-fox** [sli-fox/Mongoose#10]
Hey JM,

I'm not sure if there's something wrong with the install of the Xam.Plugins.Settings package and the Refactored.Xam....blahblah references that are made when installed.

Here's the issue:
On Global-settings-page branch
I created a SettingsTests.cs file with a DefaultSettingsTest.
I originally have this test run under the Mongoose.Droid.Tests project -- but then I get the following error when the test runs.
"System.NotImplementedException : This functionality is not implemented in the portable version of this assembly.  You should reference the Xam.Plugins.Settings NuGet package from your main application project in order to reference the platform-specific implementation."
So then I realize that Mongoose.Droid.Tests doesn't allow the install of packages, so I move my SettingsTests.cs file over to the Mongoose.Tests project where it currently still is.
I add the Xam.Plugins.Settings package to the Mongoose.Tests project and it also installs the 2 references in the .Tests project.
I run the DefaultSettingsTest in SettingsTests.cs again, this time under the Mongoose.Tests project and I get the same error mentioned above.

Is there anything you see that I'm doing wrong?

**Comment by LdTrigger** [comment]
This is the error I was getting that made me think it needed to be tested on Droid.Test. I'll take a look at it.

**Comment by LdTrigger** [comment]
Side note, I was able to install a package to Droid.Test easily

**Comment by LdTrigger** [comment]
I got it to work without a problem. Test fails, by the way. You might need to check your Xamarin configuration, since Droid.Tests has no issues installing packages
